// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MatrixFactorizationML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("UserId"), LoadColumn(1)]
        public float UserId { get; set; }


        [ColumnName("SongId"), LoadColumn(2)]
        public float SongId { get; set; }


        [ColumnName("Rate"), LoadColumn(3)]
        public float Rate { get; set; }


    }
}
