// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongRecommendation.Data;

namespace SongRecommendation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210517201202_addUserGradesToDatabaseBetter")]
    partial class addUserGradesToDatabaseBetter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SongRecommendation.Model.Genre", b =>
                {
                    b.Property<string>("Genre1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Genre");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("SongRecommendation.Model.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("genre");

                    b.Property<string>("Mood")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mood");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SongRecommendation.Model.SongsDb", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("artist_name");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("int")
                        .HasColumnName("release_id");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("release_name");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("song_id");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("terms");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("SongsDB");
                });

            modelBuilder.Entity("SongRecommendation.Model.UserGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("SongId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
